name: json_theme
description: A library to dynamically generate a ThemeData object from a JSON file or dynamic map object
homepage: https://github.com/peiffer-innovations/json_theme

version: 4.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  json_class: ^2.1.2+4
  json_schema2: ^2.0.2
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
