name: json_theme
description: A library to dynamically generate a ThemeData object from a JSON file or dynamic map object
homepage: https://github.com/peiffer-innovations/json_theme

version: 0.1.2

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  json_class: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
