name: 'json_theme'
description: 'A library to dynamically generate a ThemeData object from a JSON file or dynamic map object'
homepage: 'https://github.com/peiffer-innovations/json_theme'
version: '4.0.0+5'

environment: 
  sdk: '>=2.17.0 <3.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'


dependencies: 
  flutter: 
    sdk: 'flutter'
  json_class: '^2.1.2+7'
  json_schema2: '^2.0.2+5'
  meta: '^1.7.0'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
