name: json_theme
description: A library to dynamically generate a ThemeData object from a JSON file or dynamic map object
homepage: https://github.com/peiffer-innovations/json_theme

version: 2.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  json_class: ^2.0.0
  json_schema2: ^2.0.0+1
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
