builders:
  decoder_builder:
    import: 'package:json_theme_codegen/builder.dart'
    builder_factories: ['decoderLibrary']
    build_extensions: { '.dart': ['decoder.g.part'] }
    auto_apply: dependents
    build_to: source
    # applies_builders: ['source_gen|combining_builder']
