name: 'json_theme_codegen'
description: 'A library to generate the mapping of decoders to the class names they decode'
homepage: 'https://github.com/peiffer-innovations/json_theme'
version: '1.0.0+1'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'

dependencies:
  analyzer: '^5.13.0'
  build: '^2.4.0'
  build_runner: '^2.4.5'
  code_builder: '^4.4.0'
  json_class: '^2.2.1+3'
  json_theme_annotation: '^1.0.0+1'
  recase: '^4.1.0'
  source_gen: '^1.2.7'

dev_dependencies:
  test: '^1.24.3'

# dependency_overrides:
#   json_theme_annotation:
#     path: ../annotation

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
